// Code generated by Kitex v0.9.1. DO NOT EDIT.

package videoservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	video "tiktokrpc/kitex_gen/video"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Feed(ctx context.Context, req *video.FeedRequest, callOptions ...callopt.Option) (r *video.FeedResponse, err error)
	Upload(ctx context.Context, req *video.UploadRequest, callOptions ...callopt.Option) (r *video.UploadResponse, err error)
	UploadList(ctx context.Context, req *video.UploadListRequest, callOptions ...callopt.Option) (r *video.UploadListResponse, err error)
	Rank(ctx context.Context, req *video.RankRequest, callOptions ...callopt.Option) (r *video.RankResponse, err error)
	Query(ctx context.Context, req *video.QueryRequest, callOptions ...callopt.Option) (r *video.QueryResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) Feed(ctx context.Context, req *video.FeedRequest, callOptions ...callopt.Option) (r *video.FeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, req)
}

func (p *kVideoServiceClient) Upload(ctx context.Context, req *video.UploadRequest, callOptions ...callopt.Option) (r *video.UploadResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Upload(ctx, req)
}

func (p *kVideoServiceClient) UploadList(ctx context.Context, req *video.UploadListRequest, callOptions ...callopt.Option) (r *video.UploadListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadList(ctx, req)
}

func (p *kVideoServiceClient) Rank(ctx context.Context, req *video.RankRequest, callOptions ...callopt.Option) (r *video.RankResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Rank(ctx, req)
}

func (p *kVideoServiceClient) Query(ctx context.Context, req *video.QueryRequest, callOptions ...callopt.Option) (r *video.QueryResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Query(ctx, req)
}
