Service:
    Host: 0.0.0.0
    Port: 10002

Etcd:
    Host: 127.0.0.1
    Port: 2380

Jaeger:
    Host: 127.0.0.1
    Port: 6831

MySQL:
    UserName: username
    PassWord: password
    Host: 100.120.229.157
    Port: 3306
    Name: databasename

