// Code generated by hertz generator.

package interact

import (
	"github.com/cloudwego/hertz/pkg/app"
	"tiktokrpc/cmd/api/biz/router/auth"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _comment0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _like0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likelistMw() []app.HandlerFunc {
	// your code...
	return nil
}
