Service:
    Host: 0.0.0.0
    Port: 10001

Etcd:
    Host: tiktok-etcd
    Port: 2379

Jaeger:
    Host: tiktok-etcd
    Port: 6831

MySQL:
    UserName: username
    PassWord: password
    Host: tiktok-etcd
    Port: 3306
    Name: databasename

Redis:
    UserName: default
    PassWord: lty20050530
    Host: tiktok-etcd
    Port: 6379