// Code generated by Kitex v0.9.1. DO NOT EDIT.

package interactservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	interact "tiktokrpc/kitex_gen/interact"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Like": kitex.NewMethodInfo(
		likeHandler,
		newInteractServiceLikeArgs,
		newInteractServiceLikeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LikeList": kitex.NewMethodInfo(
		likeListHandler,
		newInteractServiceLikeListArgs,
		newInteractServiceLikeListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Comment": kitex.NewMethodInfo(
		commentHandler,
		newInteractServiceCommentArgs,
		newInteractServiceCommentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CommentList": kitex.NewMethodInfo(
		commentListHandler,
		newInteractServiceCommentListArgs,
		newInteractServiceCommentListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteComment": kitex.NewMethodInfo(
		deleteCommentHandler,
		newInteractServiceDeleteCommentArgs,
		newInteractServiceDeleteCommentResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	interactServiceServiceInfo                = NewServiceInfo()
	interactServiceServiceInfoForClient       = NewServiceInfoForClient()
	interactServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return interactServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return interactServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return interactServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "interactService"
	handlerType := (*interact.InteractService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "interact",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func likeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interact.InteractServiceLikeArgs)
	realResult := result.(*interact.InteractServiceLikeResult)
	success, err := handler.(interact.InteractService).Like(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractServiceLikeArgs() interface{} {
	return interact.NewInteractServiceLikeArgs()
}

func newInteractServiceLikeResult() interface{} {
	return interact.NewInteractServiceLikeResult()
}

func likeListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interact.InteractServiceLikeListArgs)
	realResult := result.(*interact.InteractServiceLikeListResult)
	success, err := handler.(interact.InteractService).LikeList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractServiceLikeListArgs() interface{} {
	return interact.NewInteractServiceLikeListArgs()
}

func newInteractServiceLikeListResult() interface{} {
	return interact.NewInteractServiceLikeListResult()
}

func commentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interact.InteractServiceCommentArgs)
	realResult := result.(*interact.InteractServiceCommentResult)
	success, err := handler.(interact.InteractService).Comment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractServiceCommentArgs() interface{} {
	return interact.NewInteractServiceCommentArgs()
}

func newInteractServiceCommentResult() interface{} {
	return interact.NewInteractServiceCommentResult()
}

func commentListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interact.InteractServiceCommentListArgs)
	realResult := result.(*interact.InteractServiceCommentListResult)
	success, err := handler.(interact.InteractService).CommentList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractServiceCommentListArgs() interface{} {
	return interact.NewInteractServiceCommentListArgs()
}

func newInteractServiceCommentListResult() interface{} {
	return interact.NewInteractServiceCommentListResult()
}

func deleteCommentHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interact.InteractServiceDeleteCommentArgs)
	realResult := result.(*interact.InteractServiceDeleteCommentResult)
	success, err := handler.(interact.InteractService).DeleteComment(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractServiceDeleteCommentArgs() interface{} {
	return interact.NewInteractServiceDeleteCommentArgs()
}

func newInteractServiceDeleteCommentResult() interface{} {
	return interact.NewInteractServiceDeleteCommentResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Like(ctx context.Context, req *interact.LikeRequest) (r *interact.LikeResponse, err error) {
	var _args interact.InteractServiceLikeArgs
	_args.Req = req
	var _result interact.InteractServiceLikeResult
	if err = p.c.Call(ctx, "Like", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LikeList(ctx context.Context, req *interact.LikeListRequest) (r *interact.LikeListResponse, err error) {
	var _args interact.InteractServiceLikeListArgs
	_args.Req = req
	var _result interact.InteractServiceLikeListResult
	if err = p.c.Call(ctx, "LikeList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Comment(ctx context.Context, req *interact.CommentRequest) (r *interact.CommentResponse, err error) {
	var _args interact.InteractServiceCommentArgs
	_args.Req = req
	var _result interact.InteractServiceCommentResult
	if err = p.c.Call(ctx, "Comment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentList(ctx context.Context, req *interact.CommentListRequest) (r *interact.CommentListResponse, err error) {
	var _args interact.InteractServiceCommentListArgs
	_args.Req = req
	var _result interact.InteractServiceCommentListResult
	if err = p.c.Call(ctx, "CommentList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteComment(ctx context.Context, req *interact.DeleteCommentRequest) (r *interact.DeleteCommentResponse, err error) {
	var _args interact.InteractServiceDeleteCommentArgs
	_args.Req = req
	var _result interact.InteractServiceDeleteCommentResult
	if err = p.c.Call(ctx, "DeleteComment", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
