// Code generated by hertz generator.

package social

import (
	"github.com/cloudwego/hertz/pkg/app"
	"tiktokrpc/cmd/api/biz/router/auth"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fanlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _starlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _starMw() []app.HandlerFunc {
	// your code...
	return nil
}
