# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\x08Response\x12\r\n\x05reply\x18\x01 \x01(\t24\n\x0e\x45xampleService\x12\"\n\x0bSendMessage\x12\x08.Request\x1a\t.ResponseB\x03\x80\x01\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_REQUEST']._serialized_start=14
  _globals['_REQUEST']._serialized_end=40
  _globals['_RESPONSE']._serialized_start=42
  _globals['_RESPONSE']._serialized_end=67
  _globals['_EXAMPLESERVICE']._serialized_start=69
  _globals['_EXAMPLESERVICE']._serialized_end=121
# @@protoc_insertion_point(module_scope)
