Service:
    Host: 0.0.0.0
    Port: 10003

Etcd:
    Host: 10.233.121.132
    Port: 2379

Jaeger:
    Host: 10.233.121.132
    Port: 6831

MySQL:
    UserName: username
    PassWord: password
    Host: 10.233.121.132
    Port: 3306
    Name: databasename
