Service:
    Addr: 127.0.0.1
    Port: 10003

Etcd:
    Addr: 127.0.0.1
    Port: 2379

MySQL:
    UserName:  west
    PassWord:  west123
    Host:  100.120.229.157
    Port:  3306
    Name:  west

Redis:
    UserName:  default
    PassWord:  lty20050530
    Host:  100.120.229.157
    Port:  6379

QiNiu:
    Bucket:  westonline
    AccessKey:  bP9vDYTmRFeZIYpnqOUS7xejkV4o0M5P1ptXIYFb
    SecretKey:  KCLj9p1AmC8Gvq6WBKkUg8Eg2lt5eB0nYt_peWjh
    Domain:  http://test.fzuer.xyz/

Sentinel:
    Threshold:  100
    StatIntervalInMs:  1000