// Code generated by hertz generator.

package user

import (
	"github.com/cloudwego/hertz/pkg/app"
	"tiktokrpc/cmd/api/biz/router/auth"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _mfaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfa0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfagetMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _mfastatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _infoMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avatarMw() []app.HandlerFunc {
	// your code...
	return auth.Auth()
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}
