// Code generated by Kitex v0.9.1. DO NOT EDIT.

package socialservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	social "tiktokrpc/kitex_gen/social"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Star(ctx context.Context, req *social.StarRequest, callOptions ...callopt.Option) (r *social.StarResponse, err error)
	StarList(ctx context.Context, req *social.StarListRequest, callOptions ...callopt.Option) (r *social.StarListResponse, err error)
	FanList(ctx context.Context, req *social.FanListRequest, callOptions ...callopt.Option) (r *social.FanListResponse, err error)
	FriendList(ctx context.Context, req *social.FriendListRequest, callOptions ...callopt.Option) (r *social.FriendListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kSocialServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSocialServiceClient struct {
	*kClient
}

func (p *kSocialServiceClient) Star(ctx context.Context, req *social.StarRequest, callOptions ...callopt.Option) (r *social.StarResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Star(ctx, req)
}

func (p *kSocialServiceClient) StarList(ctx context.Context, req *social.StarListRequest, callOptions ...callopt.Option) (r *social.StarListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StarList(ctx, req)
}

func (p *kSocialServiceClient) FanList(ctx context.Context, req *social.FanListRequest, callOptions ...callopt.Option) (r *social.FanListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FanList(ctx, req)
}

func (p *kSocialServiceClient) FriendList(ctx context.Context, req *social.FriendListRequest, callOptions ...callopt.Option) (r *social.FriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, req)
}
