// Code generated by hertz generator.

package user

import (
	"context"
	"tiktokrpc/cmd/api/biz/middleware/jwt"
	"tiktokrpc/cmd/api/biz/pack"
	"tiktokrpc/cmd/api/biz/service"

	"github.com/cloudwego/hertz/pkg/app"
	"tiktokrpc/cmd/api/biz/model/user"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.RegisterResponse)

	resp, err = service.NewUserService(ctx, c).Register(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	pack.SendResponse(c, resp)
}

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.LoginResponse)

	resp, err = service.NewUserService(ctx, c).Login(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	jwt.AccessTokenJwtMiddleware.LoginHandler(ctx, c)
	jwt.RefreshTokenJwtMiddleware.LoginHandler(ctx, c)

	c.Header("Access-Token", c.GetString("Access-Token"))
	c.Header("Refresh-Token", c.GetString("Refresh-Token"))

	pack.SendResponse(c, resp)
}

// Info .
// @router /user/info [GET]
func Info(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.InfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.InfoResponse)

	resp, err = service.NewUserService(ctx, c).Info(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	pack.SendResponse(c, resp)
}

// Upload .
// @router /user/avatar/upload [PUT]
func Upload(ctx context.Context, c *app.RequestContext) {

	data, err := c.FormFile("data")
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.UploadResponse)

	resp, err = service.NewUserService(ctx, c).Upload(data)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	pack.SendResponse(c, resp)
}

// MFAGet .
// @router /auth/mfa/qrcode [GET]
func MFAGet(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.MFAGetRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.MFAGetResponse)

	resp, err = service.NewUserService(ctx, c).MFAGet(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	pack.SendResponse(c, resp)
}

// MFA .
// @router /auth/mfa/bind [POST]
func MFA(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.MFABindRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.MFABindResponse)

	resp, err = service.NewUserService(ctx, c).MFA(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	pack.SendResponse(c, resp)
}

// MFAStatus .
// @router /auth/mfa/status [POST]
func MFAStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.MFAStatusRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.MFAStatusResponse)

	resp, err = service.NewUserService(ctx, c).MFAStatus(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	pack.SendResponse(c, resp)
}
