Service:
    Host: 0.0.0.0
    Port: 10000
    WebsocketPort: 9999

Etcd:
    Host: 127.0.0.1
    Port: 2380

Jaeger:
    Host: 127.0.0.1
    Port: 6831

MySQL:
    UserName: username
    PassWord: password
    Host: 100.120.229.157
    Port: 3306
    Name: databasename

Redis:
    UserName: default
    PassWord: lty20050530
    Host: 100.120.229.157
    Port: 6379

QiNiu:
    Bucket: bucketname
    AccessKey: accesskey
    SecretKey: secretkey
    Domain: http://test.qinui.com/

Sentinel:
    Threshold: 100
    StatIntervalInMs: 1