// Code generated by hertz generator.

package social

import (
	"context"
	"tiktokrpc/cmd/api/biz/pack"
	"tiktokrpc/cmd/api/biz/service"

	"github.com/cloudwego/hertz/pkg/app"
	"tiktokrpc/cmd/api/biz/model/social"
)

// Star .
// @router /relation/action [POST]
func Star(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.StarRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(social.StarResponse)

	resp, err = service.NewSocialService(ctx, c).Star(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	pack.SendResponse(c, resp)
}

// StarList .
// @router /following/list [GET]
func StarList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.StarListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(social.StarListResponse)

	resp, err = service.NewSocialService(ctx, c).StarList(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	pack.SendResponse(c, resp)
}

// FanList .
// @router /follower/list [GET]
func FanList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FanListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(social.FanListResponse)

	resp, err = service.NewSocialService(ctx, c).FanList(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	pack.SendResponse(c, resp)
}

// FriendList .
// @router /friends/list [GET]
func FriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req social.FriendListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(social.FriendListResponse)

	resp, err = service.NewSocialService(ctx, c).FriendList(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	pack.SendResponse(c, resp)
}
